AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for a serverless web app backend

Resources:
  FormTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FormSubmissions
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FormSubmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handleFormSubmit.handler
      Runtime: nodejs20.x
      CodeUri: s3://amzstorepage/351ebac898104bc9f6d48c49fec301b1
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref FormTable
      Events:
        FormSubmitApi:
          Type: Api
          Properties:
            Path: /submitForm
            Method: post
            RestApiId: !Ref ServerlessRestApi

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ourApi
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "our API"
          version: "1.0"
        paths:
          /submitForm:
            post:
              produces:
                - application/json
              consumes:
                - application/json
              responses:
                '200':
                  description: "Success"
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FormSubmitFunction.Arn}/invocations
                httpMethod: POST
                passthroughBehavior: when_no_match
                contentHandling: CONVERT_TO_TEXT
      Cors:
        AllowMethods: "'OPTIONS,POST,GET'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'https://amz-photography.vercel.app'"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submitForm

