AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for a serverless web app backend
Resources:
  FormTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FormSubmissions
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      SamResourceId: FormTable
  FormSubmitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handleFormSubmit.handler
      Runtime: nodejs20.x
      CodeUri: s3://amzstorepage/351ebac898104bc9f6d48c49fec301b1
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME:
            Ref: FormTable
      Events:
        FormSubmitApi:
          Type: Api
          Properties:
            Path: /submitForm
            Method: post
    Metadata:
      SamResourceId: FormSubmitFunction
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submitForm
